### ISSUE TITLE
关于 hset  upstream_key 问题 

### ISSUE THREAD

**Issue by Donghui0** [CMGS/elb#2]
hi:
    发现 load_upstream 中 使用 hgetall UPSTREAM_KEY 来解决初始化问题.  但何时用 hset 来写入数据呢?   subscribe channel  返回的 update 也只是进行了 router.add_upstream 并没有持久化到 redis 中?  难道是需要其他的组件来使用 elb_client  写入么 ?

    目前看来设计上是想让一台 ELB 只处理一个域名. 多域名部署到一台 elb 创建多份 config 就可以了吧.
    你们会固定住 ELB 的 IP 么 ?  

3ks

**Comment by ZhangYet** [comment]
@Donghui0 这是年轻时候犯的错，目前是 citadel 将数据持久化的。即将改。

**Comment by CMGS** [comment]
@Donghui0 其实 ELB 的发展历程经历了若干个版本…我们之前想要达到的目的是无论一台 ELB 上有几个域名，都应该通过 ELB 的 filters 筛选来找到对应的一组容器。

现在的这个永乐版本是基于我之前写的朱标那一版，那一版里面其实就有你说的 hset 写入数据。具体逻辑是通过 API 改变 router 表之后，API 会 dump 一份数据到 redis 之中，这样当 ELB 重启的时候就不需要额外第三方的工具重刷一轮路由表了。

之所以改为现在这种样子是之前我们实际生产中遇到了一个小问题，就是当 API 刷新失败了怎么办？事实上对于我们所部署的云端环境来说，由于容器上下线的频度比较高，导致了这个发生的几率有点大。因此在永乐这个版本上我们暂时性的去掉了这个实现，也就是说只要 ELB 出问题（重启，不同步 etc），均需要靠 citadel 全量重刷路由表来解决。这也就是上面 @ZhangYet 讲的年轻时的错误了。

最后对于 ELB 处理域名来说，一个 ELB 是不限制域名多少的，每个域名都会通过不同的规则导入到不同的容器组中，在实现上是通过改变 nginx access 流程来访问 router filters 引流，配置上是完全动态化的。

**Comment by CMGS** [comment]
@all

ENJOY 内部已经往 elb4 升级了……这个项目可以关了，具体进度可以参考 https://github.com/projecteru2/elb
